name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./GoaItService.csproj

      - name: Build
        run: dotnet build ./GoaItService.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish ./GoaItService.csproj -c Release -o ./publish --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: ./publish
``
